[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
evm_version = "london"
solc = "0.8.27"
optimizer = true
optimizer_runs = 200
block_gas_limit = 8000000
verbosity=2

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
flare = "https://flare-api.flare.network/ext/C/rpc"
coston2 = "https://coston2-api.flare.network/ext/C/rpc"

[fmt]
sort_imports=true